addSbtPlugin("org.xerial.sbt"  % "sbt-sonatype" % "2.3")
addSbtPlugin("com.jsuereth"    % "sbt-pgp"      % "1.1.1")
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.1.0-M7")
addSbtPlugin("com.geirsson"    % "sbt-scalafmt" % "1.5.1")
addSbtPlugin("com.dwijnand"    % "sbt-dynver"   % "3.1.0")
